//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("CISample")]
[assembly: AssemblyDescription("Universal Windows Platform App")]
[assembly: AssemblyProduct("CISample")]
[assembly: AssemblyVersion("0.0.4")]
[assembly: AssemblyFileVersion("0.0.4")]
[assembly: AssemblyInformationalVersion("0.0.4-dev4")]
[assembly: AssemblyCopyright("Copyright (c) Dachi Gogotchuri - 2016")]

